CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(40)    NOT NULL,
    description VARCHAR(120),
    price       NUMERIC(19, 2) NOT NULL,
    img_url     VARCHAR(255)
);