CREATE TABLE tb_order
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment       TIMESTAMP WITH TIME ZONE NOT NULL,
    client_id    BIGINT,

    order_status INTEGER,

    CONSTRAINT fk_order_client
        FOREIGN KEY (client_id)
            REFERENCES tb_user (id)
);